<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0" PrivateAssets="All" />
    <Protobuf Include="Protos/sms.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
